### ISSUE TITLE
Should there be a (blank) __init__.py in the gaia_interchange directory?

### ISSUE THREAD

**Issue by rogerbock** [isi-vista/gaia-interchange#44]
I think if you don't have the __init__.py file aifutils can't import gaia_interchange.aida_rdf_ontologies:

`ImportError: No module named gaia_interchange.aida_rdf_ontologies`

Once I touch that file, I can import gaia_interchange.aifutils and everything works fine.

**Comment by rgabbard** [comment]
@rogerbock : Thanks for catching that. Can you confirm it is fixed for you by the recent commit b680e2d ?

**Comment by rogerbock** [comment]
Fixed now.  Thanks @rgabbard!
